// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Test documents
 */
interface TestDocumentData {
  /**
   * username field in *Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Test.username
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  username: prismic.KeyTextField;

  /**
   * password field in *Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Test.password
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  password: prismic.KeyTextField;

  /**
   * manimage field in *Test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Test.manimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  manimage: prismic.ImageField<never>;
}

/**
 * Test document from Prismic
 *
 * - **API ID**: `Test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TestDocumentData>, "Test", Lang>;

/**
 * Item in *CardColmun → card*
 */
export interface CardcolmunfirstDocumentDataCardItem {
  /**
   * logo field in *CardColmun → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.card[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * subtitle field in *CardColmun → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.card[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * subtext field in *CardColmun → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.card[].subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;
}

type CardcolmunfirstDocumentDataSlicesSlice = never;

/**
 * Content for CardColmun documents
 */
interface CardcolmunfirstDocumentData {
  /**
   * title field in *CardColmun*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link1 field in *CardColmun*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.link1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link1: prismic.KeyTextField;

  /**
   * card field in *CardColmun*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardcolmunfirstDocumentDataCardItem>>;

  /**
   * Slice Zone field in *CardColmun*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardcolmunfirstDocumentDataSlicesSlice> /**
   * Meta Title field in *CardColmun*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cardcolmunfirst.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *CardColmun*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cardcolmunfirst.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *CardColmun*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunfirst.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * CardColmun document from Prismic
 *
 * - **API ID**: `cardcolmunfirst`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardcolmunfirstDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardcolmunfirstDocumentData>,
    "cardcolmunfirst",
    Lang
  >;

/**
 * Item in *ColThreeWithCards → card*
 */
export interface CardcolmunsecondDocumentDataCardItem {
  /**
   * logo field in *ColThreeWithCards → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.card[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * subtitle field in *ColThreeWithCards → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.card[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * subtext field in *ColThreeWithCards → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.card[].subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;
}

type CardcolmunsecondDocumentDataSlicesSlice = never;

/**
 * Content for ColThreeWithCards documents
 */
interface CardcolmunsecondDocumentData {
  /**
   * title field in *ColThreeWithCards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link field in *ColThreeWithCards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * card field in *ColThreeWithCards*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardcolmunsecondDocumentDataCardItem>>;

  /**
   * Slice Zone field in *ColThreeWithCards*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardcolmunsecondDocumentDataSlicesSlice> /**
   * Meta Title field in *ColThreeWithCards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cardcolmunsecond.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ColThreeWithCards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cardcolmunsecond.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ColThreeWithCards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolmunsecond.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ColThreeWithCards document from Prismic
 *
 * - **API ID**: `cardcolmunsecond`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardcolmunsecondDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardcolmunsecondDocumentData>,
    "cardcolmunsecond",
    Lang
  >;

/**
 * Item in *ColThreeCardWrapper → card*
 */
export interface CardcolumnsecondDocumentDataCardItem {
  /**
   * logo field in *ColThreeCardWrapper → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.card[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * subtitle field in *ColThreeCardWrapper → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.card[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * subtext field in *ColThreeCardWrapper → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.card[].subtext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;
}

type CardcolumnsecondDocumentDataSlicesSlice = never;

/**
 * Content for ColThreeCardWrapper documents
 */
interface CardcolumnsecondDocumentData {
  /**
   * title field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * link field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * card field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardcolumnsecondDocumentDataCardItem>>;

  /**
   * Slice Zone field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardcolumnsecondDocumentDataSlicesSlice> /**
   * Meta Title field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cardcolumnsecond.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cardcolumnsecond.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ColThreeCardWrapper*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardcolumnsecond.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ColThreeCardWrapper document from Prismic
 *
 * - **API ID**: `cardcolumnsecond`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardcolumnsecondDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardcolumnsecondDocumentData>,
    "cardcolumnsecond",
    Lang
  >;

/**
 * Item in *CardGrid → card*
 */
export interface CardgridDocumentDataCardItem {
  /**
   * logo field in *CardGrid → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * subhead field in *CardGrid → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[].subhead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subhead: prismic.KeyTextField;

  /**
   * subtitle field in *CardGrid → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * link field in *CardGrid → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * bgcardimg field in *CardGrid → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[].bgcardimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bgcardimg: prismic.ImageField<never>;

  /**
   * title field in *CardGrid → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

type CardgridDocumentDataSlicesSlice = never;

/**
 * Content for CardGrid documents
 */
interface CardgridDocumentData {
  /**
   * card field in *CardGrid*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.card[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardgridDocumentDataCardItem>>;

  /**
   * title field in *CardGrid*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *CardGrid*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardgridDocumentDataSlicesSlice> /**
   * Meta Title field in *CardGrid*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cardgrid.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *CardGrid*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cardgrid.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *CardGrid*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardgrid.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * CardGrid document from Prismic
 *
 * - **API ID**: `cardgrid`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardgridDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardgridDocumentData>,
    "cardgrid",
    Lang
  >;

type CardwithbuttonDocumentDataSlicesSlice = never;

/**
 * Content for CardWithButton documents
 */
interface CardwithbuttonDocumentData {
  /**
   * title field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subhead field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.subhead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subhead: prismic.KeyTextField;

  /**
   * subtitle field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * button field in *CardWithButton*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * secondsubhead field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.secondsubhead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondsubhead: prismic.KeyTextField;

  /**
   * secondsubtitle field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.secondsubtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondsubtitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *CardWithButton*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CardwithbuttonDocumentDataSlicesSlice> /**
   * Meta Title field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: cardwithbutton.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *CardWithButton*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: cardwithbutton.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *CardWithButton*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardwithbutton.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * CardWithButton document from Prismic
 *
 * - **API ID**: `cardwithbutton`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardwithbuttonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardwithbuttonDocumentData>,
    "cardwithbutton",
    Lang
  >;

type ColwithlogosDocumentDataSlicesSlice = never;

/**
 * Content for ColWithLogos documents
 */
interface ColwithlogosDocumentData {
  /**
   * title field in *ColWithLogos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * fedrampwithtextllogo field in *ColWithLogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.fedrampwithtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fedrampwithtext: prismic.ImageField<never>;

  /**
   * aicpalogo field in *ColWithLogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.aicpalogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aicpalogo: prismic.ImageField<never>;

  /**
   * pcilogo field in *ColWithLogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.pcilogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pcilogo: prismic.ImageField<never>;

  /**
   * hipaacompliant field in *ColWithLogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.hipaacompliant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hipaacompliant: prismic.ImageField<never>;

  /**
   * button field in *ColWithLogos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *ColWithLogos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ColwithlogosDocumentDataSlicesSlice> /**
   * Meta Title field in *ColWithLogos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: colwithlogos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ColWithLogos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: colwithlogos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ColWithLogos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colwithlogos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ColWithLogos document from Prismic
 *
 * - **API ID**: `colwithlogos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColwithlogosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ColwithlogosDocumentData>,
    "colwithlogos",
    Lang
  >;

type FooterctaDocumentDataSlicesSlice = never;

/**
 * Content for Footercta documents
 */
interface FooterctaDocumentData {
  /**
   * title field in *Footercta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Footercta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * backgroundImg field in *Footercta*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.backgroundimg
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundimg: prismic.ImageField<never>;

  /**
   * bluebutton field in *Footercta*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.bluebutton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bluebutton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * graybutton field in *Footercta*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.graybutton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  graybutton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Footercta*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterctaDocumentDataSlicesSlice> /**
   * Meta Title field in *Footercta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: footercta.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Footercta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: footercta.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Footercta*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footercta.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Footercta document from Prismic
 *
 * - **API ID**: `footercta`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterctaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FooterctaDocumentData>,
    "footercta",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = never;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * headerlogo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.headerlogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  headerlogo: prismic.ImageField<never>;

  /**
   * Linkfirst field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.linkfirst
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkfirst: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Linksecond field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.linksecond
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linksecond: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Linkthird field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.linkthird
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkthird: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Linkfourth field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.linkfourth
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkfourth: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * buttonsecond field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttonsecond
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonsecond: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Fifthlink field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.fifthlink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  fifthlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice> /**
   * Meta Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: header.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: header.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HerobannerDocumentDataSlicesSlice = never;

/**
 * Content for Herobanner documents
 */
interface HerobannerDocumentData {
  /**
   * herobannervideo field in *Herobanner*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: herobanner.herobannervideo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  herobannervideo: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * title field in *Herobanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: herobanner.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Herobanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: herobanner.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * buttton field in *Herobanner*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: herobanner.buttton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttton: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Herobanner*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: herobanner.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HerobannerDocumentDataSlicesSlice> /**
   * Meta Title field in *Herobanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: herobanner.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Herobanner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: herobanner.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Herobanner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: herobanner.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Herobanner document from Prismic
 *
 * - **API ID**: `herobanner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HerobannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HerobannerDocumentData>,
    "herobanner",
    Lang
  >;

type TabswithdataDocumentDataSlicesSlice = never;

/**
 * Content for TabsWithData documents
 */
interface TabswithdataDocumentData {
  /**
   * title field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * subtext field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.subtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext: prismic.KeyTextField;

  /**
   * subtext2 field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.subtext2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext2: prismic.KeyTextField;

  /**
   * subtext3 field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.subtext3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtext3: prismic.KeyTextField;

  /**
   * img field in *TabsWithData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * img2 field in *TabsWithData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.img2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img2: prismic.ImageField<never>;

  /**
   * img3 field in *TabsWithData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.img3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img3: prismic.ImageField<never>;

  /**
   * Slice Zone field in *TabsWithData*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TabswithdataDocumentDataSlicesSlice> /**
   * Meta Title field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tabswithdata.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *TabsWithData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tabswithdata.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TabsWithData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabswithdata.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * TabsWithData document from Prismic
 *
 * - **API ID**: `tabswithdata`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TabswithdataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TabswithdataDocumentData>,
    "tabswithdata",
    Lang
  >;

export type AllDocumentTypes =
  | TestDocument
  | CardcolmunfirstDocument
  | CardcolmunsecondDocument
  | CardcolumnsecondDocument
  | CardgridDocument
  | CardwithbuttonDocument
  | ColwithlogosDocument
  | FooterctaDocument
  | HeaderDocument
  | HerobannerDocument
  | TabswithdataDocument;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * herobannervideo field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.herobannervideo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  herobannervideo: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * title field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * button field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *Home → Default → Primary*
 */
export interface HomeSliceDefaultPrimary {
  /**
   * username field in *Home → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.username
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  username: prismic.KeyTextField;

  /**
   * password field in *Home → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.default.primary.password
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  password: prismic.KeyTextField;
}

/**
 * Default variation for Home Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Home*
 */
type HomeSliceVariation = HomeSliceDefault;

/**
 * Home Shared Slice
 *
 * - **API ID**: `home`
 * - **Description**: Home
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSlice = prismic.SharedSlice<"home", HomeSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      TestDocument,
      TestDocumentData,
      CardcolmunfirstDocument,
      CardcolmunfirstDocumentData,
      CardcolmunfirstDocumentDataCardItem,
      CardcolmunfirstDocumentDataSlicesSlice,
      CardcolmunsecondDocument,
      CardcolmunsecondDocumentData,
      CardcolmunsecondDocumentDataCardItem,
      CardcolmunsecondDocumentDataSlicesSlice,
      CardcolumnsecondDocument,
      CardcolumnsecondDocumentData,
      CardcolumnsecondDocumentDataCardItem,
      CardcolumnsecondDocumentDataSlicesSlice,
      CardgridDocument,
      CardgridDocumentData,
      CardgridDocumentDataCardItem,
      CardgridDocumentDataSlicesSlice,
      CardwithbuttonDocument,
      CardwithbuttonDocumentData,
      CardwithbuttonDocumentDataSlicesSlice,
      ColwithlogosDocument,
      ColwithlogosDocumentData,
      ColwithlogosDocumentDataSlicesSlice,
      FooterctaDocument,
      FooterctaDocumentData,
      FooterctaDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HerobannerDocument,
      HerobannerDocumentData,
      HerobannerDocumentDataSlicesSlice,
      TabswithdataDocument,
      TabswithdataDocumentData,
      TabswithdataDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      HomeSlice,
      HomeSliceDefaultPrimary,
      HomeSliceVariation,
      HomeSliceDefault,
    };
  }
}
